name: Compile obs-gstreamer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSYS2 environment
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-toolchain
            mingw-w64-x86_64-meson
            mingw-w64-x86_64-pkgconf
            mingw-w64-x86_64-gstreamer
            mingw-w64-x86_64-gst-plugins-base
            mingw-w64-x86_64-obs-studio

      - name: Compile Plugin
        shell: msys2 {0}
        run: |
          # Try to setup meson, if it fails, print the log so we can see why
          meson setup --buildtype release build || (cat build/meson-logs/meson-log.txt && exit 1)
          ninja -C build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: obs-gstreamer-windows
          path: build/obs-gstreamer.dll
